########## Install and configure Logstash


- name: Install logstash
  apt:
    name: logstash
    update_cache: yes
    state: present

- name: Copy logstash config file to remote machine
  copy:
    src: files/logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    mode: 644
    owner: root

- name: Restart and enable logstash
  service: 
    name: logstash
    state: restarted
    enabled: yes


